// Generated by Selenium IDE
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
public class HerokuLoginTest {
  private WebDriver driver;
  @Before
  public void setUp() {
    driver = new ChromeDriver();

  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void herokuLoginTest() {
    driver.get("https://the-internet.herokuapp.com/login");
    driver.manage().window().setSize(new Dimension(1332, 786));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("tomsmith");

    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("SuperSecretPassword!");
    
    driver.findElement(By.id("page-footer")).click();
    driver.findElement(By.cssSelector(".fa")).click();
    driver.findElement(By.cssSelector(".icon-2x")).click();
  }
}
